### ISSUE TITLE
Holistic review of non-quarkus setup chapter

### ISSUE THREAD

**Issue by domhanak** [apache/incubator-kie-kogito-docs#588]
**Goal**
Holistic review of non-quarkus [setup guides](https://sonataflow.org/serverlessworkflow/main/getting-started/learning-environment.html)

**Comment by LuboTerifaj** [comment]
I found several issues. I provided some fixes in #648 . The one improvement that should be addressed later I reported here:
- https://github.com/apache/incubator-kie-kogito-docs/issues/647

**Comment by domhanak** [comment]
Reopening this issue as some of these part were not reviewed with latest main state and only with 0.32.0 release. 
See [comment](https://github.com/apache/incubator-kie-kogito-docs/pull/648#issuecomment-2173989874)

**Comment by LuboTerifaj** [comment]
There is nothing more to review in the chapter at current stage.

The only part affected for the next release in [setup guides](https://sonataflow.org/serverlessworkflow/main/getting-started/learning-environment.html) chapter is kn workflow plugin. However, the documentation is not prepared yet and it is tracked by https://github.com/apache/incubator-kie-kogito-docs/issues/661.

In https://github.com/apache/incubator-kie-kogito-docs/issues/584 epic, there is no any specific version or branch mentioned. Since the main is not stable and it is evolving, we cannot review the "temporary" state, but we should rather focus on stable releases. The feature/changes may not be complete yet during the documentation review and the reviewing of such changes may not make sense.

I would suggest to review necessary changes under a different issue. If you think it's appropriate to track it here, feel free to keep it open. However, from my pov, it's not ideal to reopen issues like this one since we could do that over and over again as there will be coming new features and bug fixes.

I understand the documentation processes for SonataFlow project may not perfect at the moment and we do not use versioning in github issues as we used in jira, so there is certainly space for improvement in this area.

I also understand your good intention, so do it as it suits you best.

Thanks!

**Comment by domhanak** [comment]
ReReviewed latest snapshot, no changes required as of now.

I was able to spin up 10.0.x with the guide.
